name: 'Snooze issue'
description: 'commenting an issue with /snooze 30 days will temporarily close the issue for 30 days'
inputs:
  githubToken:
    description: 'github token'
    required: true
runs:
  using: 'node12'
  main: 'dist/snooze.js'
