name: snooze issue

on:
  issue_comment:
    types:
      - created

jobs:
  snooze_issue:
    runs-on: ubuntu-latest
    name: commenting an issue with /snooze 30 days will close the issue, label it snoozed and comment with data to unsnooze
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: snooze issue
        uses: ./snooze
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
